language: python
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5

install:
  - pip install -r tests/requirements.txt

script:
  - nosetests --with-coverage --cover-branches --cover-package=mdx_downheader

after_success:
  - codecov